### ISSUE TITLE
アプリの仕様をREADMEにまとめる

### ISSUE THREAD

**Issue by sakuma** [Mountain-bk/bookManagement#1]

**Comment by sakuma** [comment]
https://github.com/Mountain-bk/bookManagement/blob/bfd2a74a86791480d1c5e9f497b67e25b14269a3/README.md

* まず、追加はいいけど、直コミットではなく、PullRequest で追加しよう。
* Pythonのバージョンは、SMAPのバージョンに合わせるために、Python 3.7.x にしてよう。

**Comment by Mountain-bk** [comment]
@sakuma 
了解です。
次からはPullRequestで追加します。
Pythonのバージョンも3.7に変えました。
