### ISSUE TITLE
リポジトリに環境固有情報は入れない

### ISSUE THREAD

**Issue by sakuma** [Mountain-bk/bookManagement#2]
とくに、my\_env など

特定PCのコンパイル情報も含んでいるので、

他の人のPCや、当人だとしても、P

**Comment by Mountain-bk** [comment]
@sakuma 
my_envを削除してPullRequestします

**Comment by sakuma** [comment]
削除するだけではなく、gitで管理しないようにしないようにしないといけないです。
(.gitignore)

**Comment by Mountain-bk** [comment]
@sakuma 
.gitignoreを作成し、.venvを対象から外しました。
プルリクエストしましたので、確認お願いします。

**Comment by sakuma** [comment]
@Mountain-bk
りょうかい。
ちなみに、 ↑の書き込みのときに、  #9  でリンクにできます。

**Comment by Mountain-bk** [comment]
@sakuma 
昨日教えて頂いたのに忘れていました。
リマインドありがとうございます。
