### ISSUE TITLE
ディレクトリなどで、"library"という命名がまぎらわしい

### ISSUE THREAD

**Issue by sakuma** [Mountain-bk/bookManagement#3]
きもちはわかるが、softwareの世界で、libraryを使うと、かなり誤読しやすい

- [ ] プロジェクト名の変更
- [ ] アプリ名の変更

**Comment by Mountain-bk** [comment]
@sakuma 
教えて頂きありがとうございます。
下記の2つの対処を考えました。
1．プロジェクト（libraryProject)とアプリ（library）を削除して1から作り直す
2．名前を書き換える
少し調べた所、仕様を理解する意味も込めてオプション2で行こうと思います。
